require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '9.0'

install! 'cocoapods', deterministic_uuids: false, integrate_targets: true

target 'RNSDWebImage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  inhibit_all_warnings!
  use_native_modules!

  config = use_native_modules!
  use_react_native!(path: config['reactNativePath'])

  # Pods for RNSDWebImage
  pod 'SDWebImage', '~> 4.4.8'
  pod 'FLAnimatedImage', git: 'https://github.com/Flipboard/FLAnimatedImage.git', branch: 'master'
end

post_install do |installer|
  flipper_post_install(installer)
end
